version: "3"

services:
  solr:
    logging:
      driver: none
    build:
      context: ./solr
  integration_tests:
    image: mcr.microsoft.com/dotnet/sdk:5.0-alpine
    depends_on:
    - solr
    volumes:
    - .:/code
    - $HOME/.nuget:/root/.nuget
    working_dir: /code
    command: dotnet test SolrNet.Tests.Integration --filter 'Category=Integration'



